In [1]:
import numpy as np
import random

### chess problem

In [2]:
def generate_new_board():
    board = np.zeros((8,8))
    lt = np.array([["a","b","c","d","e","f","g","h"],[1,2,3,4,5,6,7,8]])
    return board,lt
board,lt = generate_new_board()

In [12]:
def generate_number_of_boards(number,typ):
    list_of_boards = []
    for x in range(number):
        board,lt = generate_new_board()
        if typ=="heuristic":
            y = eight_heuristic_spots(board,lt)
        elif typ=="random":
            y = eight_random_spots(board,lt)
        list_of_boards.append(y)
    return list_of_boards

In [3]:
def place_queen(board,letter,number):
    ltr_i = np.where(lt[0]==letter)[0][0]
    nmr_i = np.where(lt[1]==str(number))[0][0]
    nmr_i = np.abs(nmr_i-7)
    arr = board
    np.put(arr[nmr_i],[ltr_i],1)
    return arr

In [4]:
def eight_random_spots(board,lt):
    ls = []
    for x in range(8): #generate 8 random spots
        ls.append((lt[0][random.randint(0,7)],random.randint(1,8)))
    for x in ls:
        place_queen(board,x[0],x[1])
    return (ls)

In [5]:
def eight_heuristic_spots(board,lt):
    numbers = np.random.choice(lt[1],8,replace=False)
    letters = np.random.choice(lt[0],8,replace=False)
    ls=[]
    for i,x in enumerate(letters):
        ls.append((x,numbers[i]))
    for x in ls:
        place_queen(board,x[0],x[1])
    return (board)

In [6]:
def check(board,lt):
    ls=[]
    diagonal_collisions = 0
    linear_collisions = 0
    
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0]+1,board.shape[1])]
    diags.extend(board.diagonal(i) for i in range(board.shape[1]-1,-board.shape[0],-1))
    
    for diagonal in diags:
        y = np.flip(diagonal)
        ls.append(y) 
 
    for lst in ls:
        count = 0
        for x in lst:
            if x ==1:
                count+=1
        if count>1:
            diagonal_collisions+=count
    
    for line in board:
        count=0
        for x in line:
            if x ==1:
                count+=1
        if count>1:
            linear_collisions+=count
    
    for x in range(8):
        count = 0
        column = (board[:,x])
        for x in column:
            if x ==1:
                count+=1
        if count>1:
            linear_collisions+=count
        
    total_count = linear_collisions + diagonal_collisions
    return total_count

In [33]:
def recombinate(mom,dad,mutate):
    half = int((len(mom))/2)
    
    mom_halfs = np.split(mom,2)
    dad_halfs = np.split(dad,2)
    
    #mom_vhalfs = np.split(mom,2)
    #dad_vhalfs = np.split(dad,2)

    son = np.concatenate((mom_halfs[0],dad_halfs[0]))
    daughter = np.concatenate((mom_halfs[1],dad_halfs[1]))
      
    #verticalson = np.concatenate((mom_vhalfs[0],dad_vhalfs[0]))
    #verticaldaughter = np.concatenate((mom_vhalfs[1],dad_vhalfs[1]))
    
    a = [son,daughter]
    
    if mutate==True:
        for x in a:
            if random.random()<0.8:
                np.random.shuffle(x[random.randint(0,7)]) 
    
    return a

In [34]:
def replace(list_of_boards):
    scores = []
    dc = {}
    for x in list_of_boards:
        scores.append(check(x,lt))
    for i,x in enumerate(scores):
        dc[x]=i
    scores.sort()

    a=(recombinate(list_of_boards[dc.get(scores[0])],list_of_boards[dc.get(scores[1])],mutate=True))
    
    (list_of_boards[dc.get(scores[len(scores)-1])]) = a[0]
    (list_of_boards[dc.get(scores[len(scores)-2])]) = a[1]
    #(list_of_boards[dc.get(scores[len(scores)-1])]) = a[2]
    #(list_of_boards[dc.get(scores[len(scores)-2])]) = a[3]
    
    return list_of_boards


In [35]:
list_of_boards = generate_number_of_boards(100,"heuristic")

In [37]:
for x in range(1000):
    if x%100 == 0:
        print("iteration ",x,"lowest score = ",check(list_of_boards[0],lt))
    list_of_boards = replace(list_of_boards)

iteration  0 lowest score =  8
iteration  100 lowest score =  8
iteration  200 lowest score =  8
iteration  300 lowest score =  8
iteration  400 lowest score =  8
iteration  500 lowest score =  8
iteration  600 lowest score =  8
iteration  700 lowest score =  8
iteration  800 lowest score =  8
iteration  900 lowest score =  8


In [13]:
print(list_of_boards[0])
print(check(list_of_boards[0],lt))

[[0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
6


In [ ]:
board = generate_number_of_boards(1,"heuristic")
board = board[0]
print(board)
i=0
while i<4:
    np.random.shuffle(board[i])
    i+=1
print("\n",board)

In [26]:
print(board)
for x in range(8):
    print(board[:,x])

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
